services:
  besu:
    image: hyperledger/besu:latest
    hostname: execution
    environment:
      - "JAVA_OPTS=-Xmx8g"
    command:
      [
        "--network=mainnet",
        "--data-path=/opt/besu/data",
        "--host-allowlist=*",
        "--rpc-http-enabled",
        "--rpc-http-cors-origins=*",
        "--rpc-http-host=0.0.0.0",
        "--rpc-http-port=8545",
        "--rpc-http-api=ETH,NET,CLIQUE,DEBUG,MINER,NET,PERM,ADMIN,EEA,TXPOOL,PRIV,WEB3",
        "--rpc-ws-enabled",
        "--rpc-ws-host=0.0.0.0",
        "--rpc-ws-port=8546",
        "--max-peers=25",
        "--engine-jwt-secret=/var/lib/jwtsecret/jwt.hex",
        "--engine-host-allowlist=*",
        "--engine-rpc-enabled=true",
        "--p2p-port=30303",
      ]
    volumes:
      - /data/besu:/opt/besu/data
      - /data/jwtsecret:/var/lib/jwtsecret
    ports:
      # Map the p2p port(30303), RPC HTTP port(8545), and engine port (8551)
#      - "8545:8545"
#      - "8546:8546"
#      - "8551:8551"
      - "30303:30303/tcp"
      - "30303:30303/udp"
    networks:
        - eth
    restart: unless-stopped
    stop_grace_period: 1m

  geth:
    image: ethereum/client-go:latest
    hostname: execution
    command:
      [
        "--mainnet",
        "--datadir=/var/lib/geth",
        "--authrpc.addr=0.0.0.0",
        "--authrpc.vhosts=*",
        "--authrpc.port=8551",
        "--authrpc.jwtsecret=/var/lib/geth/ee-secret/jwtsecret",
        "--db.engine=pebble",
        "--ws",
        "--ws.addr=0.0.0.0",
        "--ws.port=8546",
        "--http",
        "--http.addr=0.0.0.0",
        "--http.port=8545",
        "--metrics",
        "--metrics.addr=0.0.0.0",
      ]
    volumes:
      - /data/geth:/var/lib/geth
      - /data/jwtsecret:/var/lib/geth/ee-secret
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
    networks:
        - eth
    restart: unless-stopped
    stop_grace_period: 1m

  erigon:
    image: erigontech/erigon:latest
    hostname: execution
    command:
      [
        "--datadir=/home/erigon/.local/share/erigon",
        "--chain=mainnet",
        "--port=30303",
        "--p2p.allowed-ports=30303,30304,30305",
        "--authrpc.addr=0.0.0.0",
        "--authrpc.vhosts=*",
        "--authrpc.port=8551",
        "--authrpc.jwtsecret=/home/erigon/.local/share/erigon/secret/jwt.hex",
        "--http",
        "--http.addr=0.0.0.0",
        "--http.port=8545",
        "--http.vhosts=*",
        "--http.corsdomain=*",
        "--ws",
        "--ws.port=8546", # double check if works
        "--maxpeers=25",
#       Do we need this?
        "--torrent.port=42069",
        "--torrent.download.rate=100mb",
        "--downloader.disable.ipv6",
        "--prune=htc", # V2 full node sync
        "--prune.r.before=11052984", # v2 full node sync based on ethd
        # "--private.api.addr=0.0.0.0:9090",
      ]
    volumes:
      - /data/erigon:/home/erigon/.local/share/erigon
      - /data/jwtsecret:/home/erigon/.local/share/erigon/secret
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
      - "30304:30304/tcp"
      - "30304:30304/udp"
      - "30305:30305/tcp"
      - "30305:30305/udp"
    networks:
      - eth   
    restart: "unless-stopped"
    stop_grace_period: 1m

  nethermind:
    image: nethermind/nethermind:latest
    hostname: execution
    command:
      [
        "--Init.BaseDbPath=/execution_data",
        "--Init.WebSocketsEnabled=true",
        "--Sync.SnapSync=true",
        "--JsonRpc.Enabled=true",
        "--JsonRpc.Host=0.0.0.0",
        "--JsonRpc.Port=8545",
        "--JsonRpc.WebSocketsPort=8546",
        "--JsonRpc.EngineHost=0.0.0.0",
        "--JsonRpc.EnginePort=8551",
        "--JsonRpc.JwtSecretFile=/jwtsecret/jwt.hex",
        "--Network.DiscoveryPort=30303",
        "--Network.P2PPort=30303",
        "--Network.MaxActivePeers=25",
        #        "--HealthChecks.Enabled=true",
        #        "--HealthChecks.UIEnabled=true",
        "--Metrics.Enabled=true",
        "--Metrics.PushGatewayUrl=http://monitoring:9091",
      ]
    volumes:
      - /data/nethermind:/execution_data
      - /data/jwtsecret:/jwtsecret
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
    networks:
      - eth
    restart: "unless-stopped"
    stop_grace_period: 1m

networks:
  eth:
    name: eth