services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    hostname: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command:
      [
        "--path.rootfs=/host",
        "--path.procfs=/host/proc",
        "--path.sysfs=/host/sys",
        "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)",
      ]
    ports:
      - "9100:9100"
    networks:
      - eth

  loki:
    image: grafana/loki:latest
    hostname: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - /data/loki-data:/tmp
    restart: "unless-stopped"
    networks:
      - eth

  promtail:
    image: grafana/promtail:latest
    hostname: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - eth

  ethereum-metrics-exporter:
    image: ethpandaops/ethereum-metrics-exporter:latest
    hostname: ethereum-metrics-exporter
    ports:
      - "9090:9090"
    command:
      [
        "--consensus-url=http://consensus:5052",
        "--execution-url=http://execution:8545",
      ]
    networks:
      - eth

networks:
  eth:
    name: eth