services:
  teku:
    image: consensys/teku:latest
    hostname: consensus
    command:
      [
        "--network=${NETWORK:-mainnet}",
        "--data-base-path=/opt/teku/data",
#        "--validators-proposer-default-fee-recipient=YOUR_WALLET",
        "--ee-endpoint=http://execution:8551",
        "--ee-jwt-secret-file=/var/lib/jwtsecret/jwt.hex",
        "--p2p-port=9000",
        "--checkpoint-sync-url=https://beaconstate-${NETWORK:-mainnet}.chainsafe.io",
        "--p2p-peer-upper-bound=100",
        "--p2p-peer-lower-bound=64",
        "--rest-api-host-allowlist=*",
        "--rest-api-enabled=true",
        "--rest-api-docs-enabled=true",
        "--rest-api-interface=0.0.0.0",
        "--rest-api-port=5052",
        "--beacon-liveness-tracking-enabled=true",
        "--validators-builder-registration-default-enabled=true",
        "--builder-endpoint=http://mev-boost:18550",
      ]
    environment:
      - "JAVA_OPTS=-Xmx8g"
    volumes:
      - /data/teku:/opt/teku/data
      - /data/jwtsecret:/var/lib/jwtsecret
    ports:
      # Map the p2p port(9000) and REST API port(5051)
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "5052:5052"
    networks:
      - eth
    restart: unless-stopped
    stop_grace_period: 1m
    
  lighthouse:
    image: sigp/lighthouse:latest
    hostname: consensus
    command:
      [
        "lighthouse",
        "bn",
        "--network=${NETWORK:-mainnet}",
        "--datadir=/var/lib/lighthouse",
        "--http",
        "--http-address=0.0.0.0",
        "--http-port=5052",
        "--http-allow-origin=*",
        "--listen-address=0.0.0.0", #makes it IPv4 only :)
        "--port=9000",
        # "--quic-port=9001",
        "--target-peers=100",
        "--execution-endpoint=http://execution:8551",
        "--execution-jwt=/var/lib/lighthouse/beacon/ee-secret/jwt.hex",
        "--checkpoint-sync-url=https://beaconstate-${NETWORK:-mainnet}.chainsafe.io",
        "--builder=http://mev-boost:18550",
        "--disable-backfill-rate-limiting",
        "--disable-self-limiter",
#        "--suggested-fee-recipient=YOUR_WALLET",
      ]
    volumes:
      - /data/lighthouse:/var/lib/lighthouse
      - /data/jwtsecret:/var/lib/lighthouse/beacon/ee-secret
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "5052:5052"
      # - "9001:9001/tcp"
      # - "9001:9001/udp"
    networks:
      - eth   
    restart: "unless-stopped"
    stop_grace_period: 1m

  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    hostname: consensus
    command:
      [
        "--${NETWORK:-mainnet}",
        "--accept-terms-of-use=true",
        "--datadir=/opt/prysm/data",
        "--http-host=0.0.0.0",
        "--http-port=5052",
        "--http-cors-domain=*", # this might need work
        # "--p2p-quic-port=9000", #defail 13000
        "--p2p-tcp-port=9000", #default 13000
        "--p2p-udp-port=9000", #default 12000
        "--execution-endpoint=http://execution:8551",
        "--jwt-secret=/var/lib/jwtsecret/jwt.hex",
        "--checkpoint-sync-url=https://beaconstate-${NETWORK:-mainnet}.chainsafe.io",
        "--http-mev-relay=http://mev-boost:18550",
      ]
    volumes:
      - /data/prysm:/opt/prysm/data
      - /data/jwtsecret:/var/lib/jwtsecret
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "5052:5052"
      # - "9001:9001/tcp"
      # - "9001:9001/udp"
      # - 127.0.0.1:4000:4000 # rpc stuff
    networks:
      - eth   
    restart: "unless-stopped"
    stop_grace_period: 1m

  lodestar:
    image: chainsafe/lodestar:latest
    hostname: consensus
    command:
      [
        "beacon",
        "--network=${NETWORK:-mainnet}",
        "--dataDir=/data",
        "--rest",
        "--rest.address=0.0.0.0",
        "--rest.port=5052",
        "--logFile=/logs/beacon.log",
        "--logFileLevel=debug",
        "--logFileDailyRotate=5",
        "--port=9000",
        "--execution.urls=http://execution:8551",
        "--jwtSecret=/var/lib/lodestar/consensus/ee-secret/jwtsecret/jwt.hex",
        "--targetPeers=100",
        "--builder",
        "--builder.url=http://mev-boost:18550",
        "--checkpointSyncUrl=https://beaconstate-${NETWORK:-mainnet}.chainsafe.io",
      ]
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "5052:5052"
    # NodeJS applications have a default memory limit of 4GB on most machines.
    # This limit is bit tight for a Mainnet node, it is recommended to raise the limit
    # since memory may spike during certain network conditions.
    environment:
      NODE_OPTIONS: --max-old-space-size=8192
    volumes:
      - /data/lodestar:/data
      - /data/lodestar-logs:/logs
      - /data/jwtsecret:/var/lib/lodestar/consensus/ee-secret/jwtsecret
    networks:
      - eth
    restart: "unless-stopped"
    stop_grace_period: 1m

networks:
  eth:
    name: eth
